{{- if .Values.butler.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.butler.name }}
    service: {{ .Values.butler.name }}
  name: {{ .Values.butler.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    {{ range $i, $var := .Values.butler.service.ports -}}
    - name: {{ $var.name }}
      port: {{ $var.port }}
      targetPort: {{ $var.port }}
    {{ end }}
  type: {{ .Values.butler.service.type}}
  selector:
    app: {{ .Values.butler.name }}
{{- end}}