version: '3'
services:

  postgres:
    image: postgres:11.8-alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=darwin
    - POSTGRES_USER=darwin
    - POSTGRES_PASSWORD=darwin
    - MAX_CONNECTIONS=300

  stubby4j:
    image: sandokandias/stubby4j-docker
    depends_on:
      - postgres
    ports:
    - 8883:8883
    environment:
      STUBBY_PORT: 8883
    volumes:
      - ./src/app/resources/stubby/integrations.yml:/usr/local/stubby.yml

  app:
    image: node:12.17.0-alpine3.9
    labels:
        com.datadoghq.ad.logs: '[{"source": "nodejs", "service": "app"}]'
    depends_on:
      - stubby4j
      - postgres
    volumes:
    - ./:/butler
    working_dir: /butler
    command: npm run start:dev
    ports:
    - 3000:3000
    environment:
        DATABASE_HOST: postgres
        MOOVE_URL: http://stubby4j:8883/moove
        DARWIN_NOTIFICATION_URL: http://stubby4j:8883/deploy/notifications
        DARWIN_UNDEPLOYMENT_CALLBACK: http://stubby4j:8883/deploy/notifications/undeployment
        DARWIN_DEPLOYMENT_CALLBACK: http://stubby4j:8883/deploy/notifications/deployment
        DARWIN_ISTIO_DEPLOYMENT_CALLBACK:  http://stubby4j:8883/deploy/notifications/istio-deployment
        SPINNAKER_URL: http://stubby4j:8883/spinnaker
        HELM_TEMPLATE_URL: http://stubby4j:8883/helm
        HELM_PREFIX_URL: http://stubby4j:8883/helm
        OCTOPIPE_URL: http://stubby4j:8883/octopipe
        DD_TRACE_ANALYTICS_ENABLED: "true"
        DD_AGENT_HOST: datadog
        DD_TRACE_AGENT_PORT: 8126
        DD_LOGS_ENABLED: "true"
  datadog:
    links:
      - app
    image: datadog/agent:latest
    ports:
      - "127.0.0.1:8126:8126"
    environment:
      DD_BIND_HOST: 0.0.0.0
      DD_API_KEY: 34f03877e54a1cb1462706275b5d9b1f
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_CONTAINER_EXCLUDE: "name:datadog"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
