# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build butler

on:
  push:
    branches: [ master ]
    paths:
      - 'butler/**'
    tags:
      - '!*'
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'butler/**'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      stubby4j:
        image: sandokandias/stubby4j-docker
        env:
          STUBBY_PORT: 8883
        options: -v ${{ github.workspace }}/src/app/resources/stubby/integrations.yml:/usr/local/stubby.yml --name stubby4j
        ports:
          - 8883:8883

    steps:
    - uses: actions/checkout@v2
      with:
        path: ~/app
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
      working-directory: ~/app/./butler
    - run: npm run build --if-present
      working-directory: ~/app/./butler
    - run: npm run test:all:cov
      env:
        CI: true
        DATABASE_HOST: localhost
        MOOVE_URL: http://localhost:8883/moove
        DARWIN_NOTIFICATION_URL: http://localhost:8883/deploy/notifications
        DARWIN_UNDEPLOYMENT_CALLBACK: http://localhost:8883/deploy/notifications/undeployment
        DARWIN_DEPLOYMENT_CALLBACK: http://localhost:8883/deploy/notifications/deployment
        DARWIN_ISTIO_DEPLOYMENT_CALLBACK:  http://localhost:8883/deploy/notifications/istio-deployment
        SPINNAKER_URL: http://localhost:8883/spinnaker
        HELM_TEMPLATE_URL: http://localhost:8883/helm
        HELM_PREFIX_URL: http://localhost:8883/helm
        OCTOPIPE_URL: http://localhost:8883/octopipe
      working-directory: ~/app/./butler
    - run: npm run lint
      working-directory: ~/app/./butler
    - uses: codecov/codecov-action@v1.0.7
      with:
        fail_ci_if_error: true
        file: ./butler/coverage/lcov.info
        flags: butler
